import { defineLegalDoc } from '../types';

// [DRAFT] Structural placeholder. The real text comes from the drafting step.
export default defineLegalDoc({
  status: 'draft',
  meta: {
    title: 'Terms of Service | LinClone',
    description:
      '[DRAFT] The terms for using LinClone: AI clones, coins and subscriptions, prohibited conduct, disclaimers and governing law.',
  },
  eyebrow: 'Legal',
  title: 'Terms of Service',
  lead: '[DRAFT] These terms set out how you may use the LinClone app and related services provided by LinClone K.K. Please read them before you start.',
  effectiveDate: '2026-11-01',
  lastUpdated: '2026-10-09',
  atAGlance: [
    { icon: 'verified', title: 'These are AI clones', body: '[DRAFT] Every creator profile is an official AI clone, not the person.' },
    { icon: 'paid', title: 'Coins are prepaid', body: '[DRAFT] Coins are a prepaid right of use bought through the App Store or Google Play.' },
    { icon: 'flag', title: 'Rules that keep people safe', body: '[DRAFT] Breaking the prohibited-conduct rules can get an account suspended.' },
  ],
  sections: [
    {
      id: 'definitions',
      heading: 'Definitions',
      blocks: [
        {
          kind: 'definitionList',
          items: [
            { term: 'Service', definition: '[DRAFT] The LinClone app and related services we provide.' },
            { term: 'AI clone', definition: '[DRAFT] A conversation partner recreated with AI, authorised by the creator.' },
            { term: 'Coins', definition: '[DRAFT] A prepaid right of use inside the Service. [[Confirm legal classification]]' },
          ],
        },
      ],
    },
    {
      id: 'account',
      heading: 'Your account',
      blocks: [
        {
          kind: 'list',
          items: [
            '[DRAFT] One account is for one person.',
            {
              text: '[DRAFT] You may not register if:',
              items: ['you are under [[age requirement]]', 'we have suspended you before'],
            },
          ],
        },
      ],
    },
    {
      id: 'ai-clones',
      heading: 'About AI clones',
      blocks: [
        {
          kind: 'callout',
          tone: 'important',
          title: 'You are talking to an AI',
          body: [
            '[DRAFT] What an AI clone says is generated by AI. It is not a statement by the creator.',
            '[DRAFT] We do not guarantee its accuracy. [[Confirm wording]]',
          ],
        },
      ],
    },
    {
      id: 'coins-and-subscriptions',
      heading: 'Coins and subscriptions',
      blocks: [
        {
          kind: 'table',
          caption: '[DRAFT] What you can buy',
          columns: ['Item', 'Bought through', 'Cancel or refund'],
          rows: [
            ['Coins', 'App Store, Google Play', '[[Refund policy]]'],
            ['Subscriptions', 'App Store, Google Play', 'Cancel in your store account'],
          ],
        },
        { kind: 'storeLinks' },
      ],
    },
    {
      id: 'prohibited',
      heading: 'Prohibited conduct',
      blocks: [
        { kind: 'paragraph', text: '[DRAFT] You must not:' },
        {
          kind: 'list',
          ordered: true,
          items: [
            'break the law or public order',
            'present an AI clone as the real person',
            'harm minors in any way (see the [Child Protection Policy](/en/policies/child-protection-policy))',
          ],
        },
      ],
    },
    {
      id: 'reporting',
      heading: 'Reporting a violation',
      blocks: [
        {
          kind: 'steps',
          items: [
            { title: 'Report in the app', body: '[DRAFT] Tap "…" on a conversation or profile, then Report.' },
            { title: 'Report by email', body: 'Write to [info@linclone.com](mailto:info@linclone.com).' },
          ],
        },
      ],
    },
    {
      id: 'termination',
      heading: 'Suspension and leaving',
      blocks: [
        {
          kind: 'paragraph',
          text: '[DRAFT] Leave any time by following [Delete your account](/en/delete-user). We may suspend accounts that break these terms.',
        },
      ],
    },
    {
      id: 'disclaimer',
      heading: 'Disclaimers',
      blocks: [
        {
          kind: 'callout',
          tone: 'warning',
          body: '[DRAFT] Our liability is limited to the extent the law allows. [[Check against consumer protection law]]',
        },
      ],
    },
    {
      id: 'governing-law',
      heading: 'Governing law',
      blocks: [
        { kind: 'paragraph', text: '[DRAFT] These terms are governed by the laws of Japan, and [[court]] has exclusive jurisdiction.' },
      ],
    },
    {
      id: 'faq',
      heading: 'Questions people ask',
      blocks: [
        {
          kind: 'faq',
          items: [
            { q: 'Do coins expire?', a: '[DRAFT] [[Confirm expiry]]' },
            { q: 'Will you tell me when the terms change?', a: '[DRAFT] We announce material changes in the app and on this page.' },
          ],
        },
      ],
    },
    {
      id: 'contact',
      heading: 'Contact',
      blocks: [
        {
          kind: 'contact',
          title: 'Questions about these terms',
          email: 'info@linclone.com',
          subject: 'Question about the Terms of Service',
          label: 'Email us',
        },
      ],
    },
  ],
  related: ['privacy', 'cookies', 'childProtection', 'support'],
});
